baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-gb"
defaultContentLanguage = "en-gb"
title = "Gianluca Fiore"
theme = "hugo-tranquilpeak-theme"
# Define how many posts should appear on a site
paginate = 10
canonifyurls = true

[permalinks]
	post = "/:year/:month/:slug/"

[taxonomies]
	tag = "tags"
	category = "categories"
	achive = "archives"

[author]
  name = "Gianluca Fiore"
  bio = "Mixology of Code, Food and Drinks"
  homepage = "https://github.com/Donearm"
  gravatarEmail = "forod.g@gmail.com"
  location = "Kraków, Poland"
  twitter = "Donearm"

[params]
	# Format dates with Go's time formatting
	dateFormat = "2 January 2006"

	# Default keywords added on all pages
	keywords = []

	sidebarBehaviour = 1
	thumbnailImage = true
	thumbnailImagePosition = "right"
	autoThumbnailImage = true
	favicon = ""
	coverImage = "oslogreen.jpg"
	imageGallery = false
	hierarchicalCategories = false
	syntaxHighlighter = "highlight.js"
	
	disqusShortname = ""
	googleAnalytics = ""
	fbAdminIds = ""
	fbAppId = ""

	[[params.sharingOptions]]
		name = "Facebook"
		icon = "fa-facebook-official"
		url = "https://www.facebook.com/sharer/sharer.php?u=%s"

	[[params.sharingOptions]]
		name = "Twitter"
		icon = "fa-twitter"
		url = "https://twitter.com/intent/tweet?text=%s"

	[params.recentposts]
		hide = false
		title = "Recent blog posts"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Home"
	identifier = "home"
	pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
	url  = "/"
	weight = 1

[[menu.main]]
	name = "Blog"
	identifier = "blog"
	pre = "<i class=\"sidebar-button-icon fa fa-lg fa-bookmark\"></i>"
	url  = "post/"
	weight = 2

[[menu.main]]
	name = "Tags"
	identifier = "tags"
	pre = "<i class=\"sidebar-button-icon fa fa-lg fa-tags\"></i>"
	url  = "/tags"
	weight = 3

[[menu.main]]
	name = "Archive"
	identifier = "archive"
	pre = "<i class=\"sidebar-button-icon fa fa-lg fa-archive\"></i>"
	url  = "/archives"
	weight = 4

[[menu.main]]
	name = "Search"
	identifier = "search"
	pre = "<i class=\"sidebar-button-icon fa fa-lg fa-search\"></i>"
	url  = "/#search"
	weight = 5

[[menu.main]]
	name = "RSS"
	identifier = "rss"
	pre = "<i class=\"sidebar-button-icon fa fa-lg fa-rss\"></i>"
	url = "/index.xml"
	weight = 6
	
[[menu.links]]
	name = "Github"
	identifier = "github"
	url = "https://github.com/Donearm"
	pre = "<i class=\"sidebar-button-icon fa fa-lg fa-github\"></i>"
	weight = 1
