baseURL:                "https://donearm.github.io"
title:                  "Gianluca Fiore"
permalinks:
    post:               /:year/:month/:title/
params:
    Subtitle:           "while alive; do sudo reboot; done"
    AuthorName:         "Gianluca Fiore"
    GitHubUser:         "Donearm"
    SidebarRecentLimit: 5
contentDir:             "content"
dataDir:                "data"
publishDir:             "public"
staticDir:              "static"
source:                 ""
themesDir:              "themes"
theme:                  "hugo-uno"
defaultExtension:       "html"
defaultLayout:          "post"
enableRobotsTXT:        true
disableKinds:           ["RSS", "404"]
enableEmoji:            false
googleAnalytics:        ""
paginate:               10
paginatePath:           "page"
# Preserve special characters in taxonomy names
preserveTaxonomyNames:  true
pygmentsStyle:          "monokai"
